### ISSUE TITLE
Broken: select node and `RET`(kill-buffer-and window) would make buffer read-only.

### ISSUE THREAD

**Issue by liuyinz** [casouri/vundo#10]
It would be better to wrap the `kill-buffer-and-window` with the 
```elisp
(with-current-buffer vundo--orig-buffer
     (setq-local inhibit-modification-hooks nil
                 buffer-read-only nil))
```
together, don't use it directly. After all, `vundo-quit` would invoke it at least.

**Comment by casouri** [comment]
Thank you! I should've know better. I changed vundo to make the original buffer read-only but didn't update other parts of the code to cooperate. It should be fixed now.

**Comment by liuyinz** [comment]
Great.
