### ISSUE TITLE
color problem when use vundo-prev or vundo-next?

### ISSUE THREAD

**Issue by liuyinz** [casouri/vundo#11]
Normal: I comment a paragraph, it changes code block's color, and I use `undo`, it uncomment back, color restore.

vundo: I comment a paragraph, it changes code block's color, and I use `vundo-prev` and `vundo-confirm`, it uncomment back, but color don't restore.

Does it relate to read-only mode ? I checkout e136164f779e9a91ef722778acc704048ba0809a, it's OK.

**Comment by casouri** [comment]
Probably because of `inhibit-modification-hooks`. Jit-lock marks changed text as unfontified and redisplay will refortify the text. I disabled `inhibit-modification-hooks` because I've encountered cases where aggresive-indent-mode messes up the buffer content. Not sure how we go about this, hmmm

**Comment by liuyinz** [comment]
That is quite annoying…

**Comment by casouri** [comment]
Ok, I removed `inhibit-modification-hooks`, neither `undo` nor `undo-tree` sets it, vundo probably shouldn't set it anyway. Even if there are baddies that tries to mess up the buffer, we now mark the buffer read-only so there shouldn't be a big problem.

**Comment by liuyinz** [comment]
Everything is just fine~
