### ISSUE TITLE
[picky] `vundo--mode-map` should not use double hyphen

### ISSUE THREAD

**Issue by ideasman42** [casouri/vundo#15]
By convention double-dash is for internal/private symbols, in the case of key-maps - this is something users are likely to want to customize.

Suggest to name this `vundo-mode-map`.

**Comment by casouri** [comment]
I initially intended `vundo--mode` to be private. But that's probably a mistake that should be corrected sooner than later. I'll change that to single dash.

**Comment by casouri** [comment]
I've renamed `vundo--mode` to `vundo-mode`.

**Comment by ideasman42** [comment]
Thanks (for some reason this didn't auto-close).
