### ISSUE TITLE
Quick comparison with undo-tree

### ISSUE THREAD

**Issue by hkjels** [casouri/vundo#22]
Since there's some prior work in this space, I think it would be useful with a short paragraph about why you would want to use `vundo` over [UndoTree](https://www.emacswiki.org/emacs/UndoTree)

**Comment by casouri** [comment]
Did that, thanks.

**Comment by ideasman42** [comment]
This can be closed now?

**Comment by hkjels** [comment]
Nice! That first line you added made me want to try it
