### ISSUE TITLE
Any plans to upstream this?

### ISSUE THREAD

**Issue by leungbk** [casouri/vundo#3]
This looks like a nice package. Do you intend to merge this at some point into Emacs 28 core?

**Comment by casouri** [comment]
Maybe this can be added to ELPA when Emacs 28 releases, if there are enough interest.

**Comment by ideasman42** [comment]
Emacs 28.1 has been released so I think this could be published to elpa/melpa.

**Comment by casouri** [comment]
Cool, I'll begin adding the missing parts.

**Comment by casouri** [comment]
Now it's on ELPA, yay!
