### ISSUE TITLE
vundo-stem-root fails when executed from a particular location

### ISSUE THREAD

**Issue by ideasman42** [casouri/vundo#30]
When running `vundo-stem-root` from a child of a branch besides the first, an assertion is raised.

Refreshing again (from calling `vundo-next` for example) shows the action is infact completed.

![vundo_stem_root](https://user-images.githubusercontent.com/1869379/161368544-2d1da70e-4d7d-4f9c-8e1c-234c44b86844.png)

I checked back to the early history of `vundo` and this appears to be a bug in the initial version (not a regression).

**Comment by casouri** [comment]
Thanks! This is a major oversight. I've now fixed it.

**Comment by ideasman42** [comment]
Thanks, as far as I'm concerned this package works perfectly for me and I expect to be using it on a daily basis from now on.
