### ISSUE TITLE
[FR/Suggestion] vundo-forward and backward bring up vundo buffer 

### ISSUE THREAD

**Issue by Inc0n** [casouri/vundo#42]
Hello, 

I uses evil, and u & C-r keys are for undo and redo for me respectively. 

Right now, it doesn't seem it is possible to bring up the vundo buffer and undo or redo right away.

If in the future there is to be integration with the evil-undo-system, IMO, it would then be beneficial to implement something like this.
Such that the following would be possible:
```
(setq evil-undo-function #'vundo-forward
        evil-redo-function #'vundo-backward)
```

What is your recommendation for this?

Thank you

**Comment by casouri** [comment]
You can just use normal undo commands: undo, undo-only,undo-redo. Vundo-forward/backward are just for moving in the visual tree.

**Comment by casouri** [comment]
Ok, I think I know you mean. Why do you want to show the tree on every undo? You would need to somehow close the vundo buffer after every undo you do and I imagine that to be quite tedious.

**Comment by Inc0n** [comment]
Ah yes silly me, I see what you mean. You are right, it would be quite tedious (closing the buffer and a small but noticable delay on `vundo`), I must admit I haven't been this package for long yet.

I think I will use vundo for visualizing the tree undo history. Haha, going to use this package as intended.
