### ISSUE TITLE
Vundo can be called inside a read-only buffer

### ISSUE THREAD

**Issue by OlMon** [casouri/vundo#48]
Hej Hej,

More of a question than an issue:
Is it intended that vundo can be called inside a read-only buffer?
If it is shouldn't the read-only state be restored after exiting vundo?

My first thoughts would be "no" and "yes", but maybe I am missing something.

Cheers and thanks for the package,
OlMon

**Comment by casouri** [comment]
Ah! Good catch, I don't think vundo should run if buffer is read-only, added a check in `vundo`. Thanks!

**Comment by OlMon** [comment]
Thanks a lot, fixed! :)
