### ISSUE TITLE
slowness with natively compiled emacs

### ISSUE THREAD

**Issue by gitrj95** [casouri/vundo#51]
not sure if others have seen this, but with lazily loaded vundo on 28, the first C-x u is strangely long

**Comment by ideasman42** [comment]
I use lazily loaded vundo in emacs-29 (compiled from master, with native compilation enabled), and don't see this problem.

**Comment by gitrj95** [comment]
hmm. let me do some profiling and get back to you. hopefully this is something reproducible

**Comment by gitrj95** [comment]
fyi you can close this. i tried to reproduce many times and wasn't able to successfully... black magic

**Comment by casouri** [comment]
That's the Emacs we love, magical ;-)
