### ISSUE TITLE
RFC: explanation of technical difficulties implementing diff

### ISSUE THREAD

**Issue by seanfarley** [casouri/vundo#54]
The readme says that diff is an advanced feature and unlikely to be supported. Would you be able to explain the challenges involved implementing such a feature?

**Comment by casouri** [comment]
I don't think there are specific challenges, it just IMO doesn't have much use to justify adding.

**Comment by seanfarley** [comment]
Ahhhh, ok; fair enough!

**Comment by jdtsmith** [comment]
See #56 for a simple implementation.  I don't always need it but it's very useful sometimes.

**Comment by jdtsmith** [comment]
@seanfarley this is now implemented, so can now be closed.

**Comment by seanfarley** [comment]
That's awesome! Yay!
