### ISSUE TITLE
Package on Melpa

### ISSUE THREAD

**Issue by xcapaldi** [casouri/vundo#65]
I really like the package and recommend it to others. For me personally, I use straight.el and pull the package directly from GitHub. However for new emacs users who are not ready for straight or loading a package manually, packaging this on Melpa would be very helpful. Do you have any plans to do this?

**Comment by casouri** [comment]
Vundo is available on ELPA, but I see that I forgot to mention it in README. I've added a notice to README. Thanks!

**Comment by xcapaldi** [comment]
Oh okay, great! Thank you
