### ISSUE TITLE
vundo--build-tree: Symbol’s function definition is void: undo--last-change-was-undo-p

### ISSUE THREAD

**Issue by NightMachinary** [casouri/vundo#7]
I get this error when I call `vundo`:
```
vundo--build-tree: Symbol’s function definition is void: undo--last-change-was-undo-p

````

**Comment by casouri** [comment]
I guess you are using Emacs 27, right? Vundo requires Emacs 28 which is not yet released. I forgot to add a notice about that in the README, thanks for reporting.
