### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by wyuenho** [casouri/vundo#70]
Hi @casouri, since vundo is not available on Melpa, I can't get the lastest changes without using something like quelpa, do you mind making a new release please? It's been a while.

**Comment by okamsn** [comment]
If it helps, GNU-devel ELPA  has a version from a few days ago:

https://elpa.gnu.org/devel/vundo.html

**Comment by wyuenho** [comment]
That's 2.0.0 tagged last year.

**Comment by wyuenho** [comment]
I don't have devel elpa as it interferes with melpa unstable

**Comment by casouri** [comment]
Yeah I'm taking a bit too long :-) I just made a release.

**Comment by wyuenho** [comment]
thank you
