### ISSUE TITLE
jit-lock errors

### ISSUE THREAD

**Issue by tmdemelo** [casouri/vundo#76]
I'm getting jit-lock errors every time I run `vundo`:

```
Error during redisplay: (jit-lock-function 1) signaled (wrong-type-argument number-or-marker-p nil)
```

Running vundo ecc0e2c3678ba1d879e1477c08c65c53b9237da6, `emacs -Q`, tested with Emacs 28 and 29.

The errors disappear when I deactivate `jit-lock-mode` via `vundo-mode-hook`.

I also noticed that, in the definition of `vundo-mode`, `jit-lock-mode` is called like this:

```elisp
(jit-lock-mode -1)
```

Perhaps you meant to deactivate `jit-lock-mode` there? If so, this is the correct (and unusual for minor-modes) form:

```elisp
(jit-lock-mode nil)
```

**Comment by casouri** [comment]
Thank you very much! That is indeed my mistake. I've pushed a fix.
