### ISSUE TITLE
Error in the customization menu

### ISSUE THREAD

**Issue by Ypot** [casouri/vundo#77]
![imagen](https://github.com/casouri/vundo/assets/30699014/afbb5d24-9389-4b0e-8299-95c39251aedc)
 In both it says the same.

**Comment by casouri** [comment]
Thank you! I pushed a fix for it.

**Comment by pierre-rouleau** [comment]
@Ypot, since this was fixed, is the fix ok for you?  If so, would you be ok to close this?

**Comment by Ypot** [comment]
Thanks. Closed!
