### ISSUE TITLE
[PR] more compat with evil and visual-line-mode

### ISSUE THREAD

**Issue by NightMachinary** [casouri/vundo#9]
You might want to incorporate this, or the package will be very unpleasant for people with other configs:
```lisp
  (defun night/h-vundo-buf-setup (orig-fn &rest args)
    (let ((vundo-buf (apply orig-fn args)))
      (with-current-buffer vundo-buf
        (toggle-truncate-lines 1)
        (evil-insert-state))
      vundo-buf))
  (advice-add 'vundo-1 :around #'night/h-vundo-buf-setup)
```

**Comment by ideasman42** [comment]
This report gives no context, what is the problem this solves?
I use evil mode and didn't see the nieed to enter `evil-insert-state` for e.g.

**Comment by NightMachinery** [comment]
You are correct, it no longer seems needed.
