### ISSUE TITLE
Love this package, thank you!

### ISSUE THREAD

**Issue by mentalisttraceur** [casouri/vundo#98]
Great package. Thank you for making it! I particularly love

1. tighter integration with Emacs' native history (it's only a matter of time before I have to code something in my config that needs to intimately manipulate/abuse history entries, in fact the prospect of doing that is what got me looking at vundo again, once I started to suspect I might have to couple my code with undo-tree (or Evil, which in turn already couples to undo-tree when both are in use) for the thing I'm trying to do), and
2. the horizontal and compact view (I use Emacs extensively on my phones!),

Love the option to use pretty unicode characters too.

~~I haven't switched from undo-tree yet, but looking at how the feature set has matured and caught up (diffs, for example) has me seriously excited about it once I start wanting any of the three benefits I just mentioned badly enough.~~ Literally right after making this post I tried switching. My config is now simpler and for the most part things are better.

**Comment by casouri** [comment]
Thanks for your kind words :-)
